-- Verify the data

SELECT COUNT(*) FROM customers;
SELECT COUNT(*) FROM orders;
SELECT COUNT(*) FROM order_items;
SELECT COUNT(*) FROM products;
SELECT COUNT(*) FROM sellers;
SELECT COUNT(*) FROM order_payments;
SELECT COUNT(*) FROM order_reviews;
SELECT COUNT(*) FROM geolocation;
SELECT COUNT(*) FROM product_category_name_translation;

--Business SQL Queries

-- 1. How many total customer are there?
SELECT COUNT(*) AS total_customers
FROM customers;

-- 2. how many total order are there?
SELECT COUNT(*) AS total_orders
FROM orders;

-- 3. how many orders have been placed for each order status?
SELECT order_status,count(*) AS total_orders_placed
FROM orders
GROUP BY order_status
ORDER BY total_orders_placed DESC;

-- 4. how many unique customers have placed order?
SELECT COUNT(DISTINCT customer_id)AS unique_customers FROM orders;

-- 5. find the top 10 city with the highest number of customers?
SELECT customer_city,
       COUNT(*) AS total_customers
FROM customers
GROUP BY customer_city
ORDER BY total_customers
limit 10;

-- 6. find the top 10 customers who placed the most orders
SELECT customer_id ,
       COUNT(order_id) AS total_orders
FROM orders
GROUP BY customer_id
ORDER BY total_orders DESC
LIMIT 10;

-- 7. find the total products
SELECT COUNT(product_id) -- this type use if the product_id are unique
FROM products;

           OR

SELECT COUNT(*) AS total_products
FROM products;

-- 8. find Total sellers
SELECT COUNT(seller_id)
FROM sellers;

-- 9. find total revenue
SELECT SUM(payment_value) AS total_revenue
FROM order_payments;

-- 10. find average payment
SELECT AVG(payment_value) AS average_payment
FROM order_payments;

-- 11. highest payment
SELECT MAX(payment_value) AS highest_payment
FROM order_payments;

-- 12. lowest payment
SELECT MIN(payment_value) AS lowest_payment
FROM order_payments;

-- 13. find top 10 most expensive order items
SELECT * FROM order_items
ORDER BY price DESC
LIMIT 10;

-- 14. find top 10 cheapest order items
SELECT * FROM order_items
ORDER BY price ASC
LIMIT 10;

-- 15. find total order by payment type
SELECT payment_type,
       COUNT(order_id) AS total_orders
FROM order_payments
GROUP BY payment_type;

-- 16. find Average product price
SELECT AVG(price) AS average_price
FROM order_items;
-- 17. Number of customers in each state
SELECT customer_state,
       COUNT(customer_id) AS total_customer
FROM customers
GROUP BY customer_state
ORDER BY total_customer DESC;

-- 18. Number of sellers in each state
SELECT seller_state,
       COUNT(seller_id) AS total_sellers
FROM sellers
GROUP BY seller_state
ORDER BY total_sellers DESC;

-- 19. find total orders by customer
SELECT customer_id,
       COUNT(order_id) AS total_orders
FROM orders
GROUP BY customer_id
ORDER BY total_orders DESC;

-- 20. find the earliest and latest order date 
SELECT MIN(order_purchase_timestamp) AS first_order,
       MAX(order_purchase_timestamp) AS last_order
FROM orders;


-- 21. find total revenue generated by each state 
SELECT c.customer_state,         
       SUM(op.payment_value) AS total_revenue
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
join order_payments op
ON o.order_id = op.order_id
GROUP BY customer_state
ORDER BY total_revenue DESC;

-- 22. find the top 10 cities by total revenue
SELECT c.customer_city, 
       SUM(op.payment_value) AS total_revenue
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN order_payments op
ON o.order_id = op.order_id
GROUP BY customer_city
ORDER BY  total_revenue DESC;
	   
-- 23. Find the Top 10 Product Categories by Revenue
SELECT
    pct.product_category_name_english,
    SUM(op.payment_value) AS total_revenue
FROM products p
JOIN product_category_name_translation pct
    ON p.product_category_name = pct.product_category_name
JOIN order_items oi
    ON p.product_id = oi.product_id
JOIN order_payments op
    ON oi.order_id = op.order_id
GROUP BY pct.product_category_name_english
ORDER BY total_revenue DESC
LIMIT 10;

-- 24. Find the Top 10 best selling product categories
SELECT
     pct.product_category_name_english,
    COUNT(oi.product_id) AS total_product_sold
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
JOIN product_category_name_translation pct
    ON p.product_category_name = pct.product_category_name
GROUP BY pct.product_category_name_english
ORDER BY total_product_sold DESC
LIMIT 10;

-- 25. find the average delivery time (in days)
SELECT 
ROUND(AVG(order_delivered_customer_date::DATE - order_purchase_timestamp::DATE),2)
FROM orders
WHERE order_delivered_customer_date IS NOT NULL;

-- 26. find the top 10 fatest delivered order
SELECT order_id,
       (order_delivered_customer_date::DATE - order_purchase_timestamp::DATE) AS delivery_days
FROM orders
WHERE order_delivered_customer_date IS NOT NULL
ORDER BY delivery_days ASC
LIMIT 10;

-- 27. Find the Top 10 States by Total Revenue
SELECT
    c.customer_state,
    SUM(op.payment_value) AS total_revenue
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_payments op
    ON o.order_id = op.order_id
GROUP BY c.customer_state
ORDER BY total_revenue DESC
LIMIT 10;

--28. Find the Monthly Revenue Trend
SELECT
    TO_CHAR(o.order_purchase_timestamp, 'YYYY-MM') AS order_month,
    SUM(op.payment_value) AS total_revenue
FROM orders o
JOIN order_payments op
    ON o.order_id = op.order_id
GROUP BY TO_CHAR(o.order_purchase_timestamp, 'YYYY-MM')
ORDER BY order_month;

-- 29. Find the Top 10 Customers by Total Spending
SELECT
    c.customer_id,
    c.customer_city,
    SUM(op.payment_value) AS total_spent
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_payments op
    ON o.order_id = op.order_id
GROUP BY c.customer_id, c.customer_city
ORDER BY total_spent DESC
LIMIT 10;


-- 30. Find the Top 10 Cities by Total Revenue
SELECT
    c.customer_city,
    SUM(op.payment_value) AS total_revenue
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_payments op
    ON o.order_id = op.order_id
GROUP BY c.customer_city
ORDER BY total_revenue DESC
LIMIT 10;

-- 31. Find the Top 10 Sellers by Total Revenue
SELECT
    s.seller_id,
    s.seller_city,
    SUM(op.payment_value) AS total_revenue
FROM sellers s
JOIN order_items oi
    ON s.seller_id = oi.seller_id
JOIN order_payments op
    ON oi.order_id = op.order_id
GROUP BY s.seller_id, s.seller_city
ORDER BY total_revenue DESC
LIMIT 10;

-- 32.Find the Average Order Value by State
SELECT
    c.customer_state,
    ROUND(AVG(op.payment_value), 2) AS average_order_value
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_payments op
    ON o.order_id = op.order_id
GROUP BY c.customer_state
ORDER BY average_order_value DESC;

-- 33. Find the Monthly Order Count
SELECT
    TO_CHAR(order_purchase_timestamp, 'YYYY-MM') AS order_month,
    COUNT(order_id) AS total_orders
FROM orders
GROUP BY TO_CHAR(order_purchase_timestamp, 'YYYY-MM')
ORDER BY order_month;

--34. Find the Top 10 Customers by Number of Orders
SELECT
    c.customer_id,
    c.customer_city,
    COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_city
ORDER BY total_orders DESC
LIMIT 10;

--35. Find the Top 10 Product Categories by Number of Orders
SELECT
    pct.product_category_name_english,
    COUNT(oi.order_id) AS total_orders
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
JOIN product_category_name_translation pct
    ON p.product_category_name = pct.product_category_name
GROUP BY pct.product_category_name_english
ORDER BY total_orders DESC
LIMIT 10;







